In [1]:
#Class Linear

In [2]:
from torch import nn
import torch

In [3]:
torch.manual_seed(1)

In [4]:
class linear_regression(nn.Module):
    def __init__(self, input_size, output_size):
        super(linear_regression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    def forward(self, x):
        yhat = self.linear(x)
        return yhat

In [17]:
model = linear_regression(1, 10)
#input:1 output:10
model((torch.tensor([1.0])))
list(model.parameters())

[Parameter containing:
 tensor([[-0.7031],
         [-0.7545],
         [ 0.0608],
         [-0.1704],
         [ 0.5873],
         [-0.5791],
         [-0.8890],
         [ 0.7278],
         [-0.1483],
         [ 0.5625]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3215, -0.7499,  0.2009,  0.2402, -0.6696, -0.4745,  0.3410,  0.1791,
         -0.4254, -0.3027], requires_grad=True)]

In [18]:
x = torch.tensor([1.0])

In [19]:
yhat = model(x)
yhat

tensor([-0.3816, -1.5044,  0.2617,  0.0698, -0.0822, -1.0536, -0.5480,  0.9069,
        -0.5737,  0.2597], grad_fn=<AddBackward0>)

In [20]:
X = torch.tensor([[1.0], [1.0], [3.0]])
yhat = model(X)
yhat

tensor([[-0.3816, -1.5044,  0.2617,  0.0698, -0.0822, -1.0536, -0.5480,  0.9069,
         -0.5737,  0.2597],
        [-0.3816, -1.5044,  0.2617,  0.0698, -0.0822, -1.0536, -0.5480,  0.9069,
         -0.5737,  0.2597],
        [-1.7879, -3.0134,  0.3833, -0.2710,  1.0924, -2.2119, -2.3260,  2.3624,
         -0.8702,  1.3847]], grad_fn=<AddmmBackward>)

# 