In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
from scipy import ndimage, misc

In [2]:
#Create 2-dimentional convolution object
conv = nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = 3)
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1))

In [4]:
conv.state_dict()['weight'][0][0]=torch.tensor([[1.0,0,-1.0],[2.0,0,-2.0],[1.0,0.0,-1.0]])
conv.state_dict()['bias'][0] = 0.0
conv.state_dict()

OrderedDict([('weight',
              tensor([[[[ 1.,  0., -1.],
                        [ 2.,  0., -2.],
                        [ 1.,  0., -1.]]]])),
             ('bias', tensor([0.]))])

In [5]:
image = torch.zeros(1, 1, 5, 5)
# number of image in our tensor, grayscale image, 5x5 pixels image
image[0,0,:,2] = 1
image

tensor([[[[0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.]]]])

In [6]:
z = conv(image)
z

tensor([[[[-4.,  0.,  4.],
          [-4.,  0.,  4.],
          [-4.,  0.,  4.]]]], grad_fn=<MkldnnConvolutionBackward>)

In [8]:
# Determining the size of the output

K = 2
# Kernel size=2
conv1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=K)
conv1.state_dict()['weight'][0][0] = torch.tensor([[1.0, 1.0],
                                                   [1.0, 1.0]
    
])
conv1.state_dict()['bias'][0] = 0.0
conv1.state_dict()
#conv1

OrderedDict([('weight',
              tensor([[[[1., 1.],
                        [1., 1.]]]])),
             ('bias', tensor([0.]))])

In [9]:
M = 4
image1 = torch.ones(1, 1, M, M)

In [11]:
z1 = conv1(image1)
print("z1:", z1)
print("shape:", z1.shape[2:4])

z1: tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]], grad_fn=<MkldnnConvolutionBackward>)
shape: torch.Size([3, 3])


In [15]:
conv3 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2, stride = 2)
conv3.state_dict()['weight'][0][0] = torch.tensor([[1.0, 1.0], [1.0, 1.0]])
conv3.state_dict()['bias'][0] = 0.0
conv3.state_dict()

OrderedDict([('weight',
              tensor([[[[1., 1.],
                        [1., 1.]]]])),
             ('bias', tensor([0.]))])

In [16]:
z3 = conv3(image1)
print("z3:", z3)
print("shape:", z3.shape[2:4])

z3: tensor([[[[4., 4.],
          [4., 4.]]]], grad_fn=<MkldnnConvolutionBackward>)
shape: torch.Size([2, 2])


In [17]:
#zero padding

In [18]:
image1

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [19]:
conv4 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2, stride=3)
conv4.state_dict()['weight'][0][0] = torch.tensor([[1.0, 1.0], [1.0, 1.0]])
conv4.state_dict()['bias'][0] = 0.0
conv4.state_dict()
z4 = conv4(image1)
print("z4:", z4)
print("z4:", z4.shape[2:4])

z4: tensor([[[[4.]]]], grad_fn=<MkldnnConvolutionBackward>)
z4: torch.Size([1, 1])


In [22]:
conv5 = nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = 2, stride = 3, padding = 1)
conv5.state_dict()['weight'][0][0] = torch.tensor([[1.0, 1.0], [1.0, 1.0]])
conv5.state_dict()['bias'][0] = 0.0
conv5.state_dict()
z5 = conv5(image1)
print("z5:", z5)
print("z5:", z5.shape[2:4])

z5: tensor([[[[1., 2.],
          [2., 4.]]]], grad_fn=<MkldnnConvolutionBackward>)
z5: torch.Size([2, 2])


In [23]:
Image = torch.randn((1, 1, 4, 4))
Image

tensor([[[[-0.3338, -0.0270, -0.7508,  0.2999],
          [ 1.0240,  0.7872,  1.1914, -0.7375],
          [-0.2051, -0.5544,  0.5447, -0.7757],
          [-0.3556, -0.8900, -0.9642, -0.8110]]]])

In [24]:
conv6 = nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size=3)
conv6.state_dict()['weight'][0][0] = torch.tensor([[0,0,0], [0,0,0], [0,0,0]])
conv6.state_dict()['bias'][0] = 0.0
z6 = conv6(Image)
print("z6:", z6)
print("z6:", z6.shape[2:4])

z6: tensor([[[[0., 0.],
          [0., 0.]]]], grad_fn=<MkldnnConvolutionBackward>)
z6: torch.Size([2, 2])


In [27]:
conv7 = nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size=2, stride=2)
conv7.state_dict()['weight'][0][0] = torch.tensor([[0,0], [0,0]])
conv7.state_dict()['bias'][0] = 0.0
z7 = conv7(Image)
print("z7:", z7)
print("z7:", z7.shape[2:4])

z7: tensor([[[[0., 0.],
          [0., 0.]]]], grad_fn=<MkldnnConvolutionBackward>)
z7: torch.Size([2, 2])
