In [1]:
#Table of contents
#Prediction
#Class Linear
#Build Custom Modules

In [2]:
#Preparation

In [3]:
import torch

In [4]:
#Prediction

In [5]:
# Define w = 2 and b = -1 for y = wx + b

w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)

In [6]:
# Function forward(x) for prediction

def forward(x):
    yhat = w * x + b
    
    return yhat

In [7]:
# Predict y = 2x - 1 at x = 1

x = torch.tensor([[1.0]])
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


In [8]:
# Create x Tensor and check the shape of x tensor

x = torch.tensor([[1.0], [2.0]])
print("The shape pf x: ", x.shape)

The shape pf x:  torch.Size([2, 1])


In [9]:
# Make the prediction of y = 2x - 1 at x = [1, 2]

yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [10]:
# Practice: Make a prediction of y = 2x - 1 at x = [[1.0], [2.0], [3.0]]

x = torch.tensor([[1.0], [2.0], [3.0]])
print("The shape of x: ", x.shape)

yhat = forward(x)
print("The prediction: ", yhat)

The shape of x:  torch.Size([3, 1])
The prediction:  tensor([[1.],
        [3.],
        [5.]], grad_fn=<AddBackward0>)


In [11]:
#class Linear

In [12]:
#Import class module

from torch.nn import Linear

In [13]:
#Set the random seed 
#because the parameters are randomly initialized:

torch.manual_seed(1)

In [24]:
# Create Linear Regression Model, 
# and print out the parameters

lr = Linear(in_features=1, out_features=1, bias=True)
print("Pararmeters w and b: ", list(lr.parameters()))

Pararmeters w and b:  [Parameter containing:
tensor([[0.5997]], requires_grad=True), Parameter containing:
tensor([-0.2057], requires_grad=True)]


In [25]:
# A method  state_dict() Returns a Python dictionary object 
#corresponding to the layers of each parameter tensor.

print("Python dictionary: ", lr.state_dict())
print("Keys: ", lr.state_dict().keys())
print("Values: ", lr.state_dict().values())

Python dictionary:  OrderedDict([('weight', tensor([[0.5997]])), ('bias', tensor([-0.2057]))])
Keys:  odict_keys(['weight', 'bias'])
Values:  odict_values([tensor([[0.5997]]), tensor([-0.2057])])


In [26]:
print("Weights: ", lr.weight)
print("Bias: ", lr.bias)

Weights:  Parameter containing:
tensor([[0.5997]], requires_grad=True)
Bias:  Parameter containing:
tensor([-0.2057], requires_grad=True)


In [27]:
# Make the prediction at x = [[1.0]]

x = torch.tensor([1.0])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([0.3940], grad_fn=<AddBackward0>)


In [29]:
# Create the prediction using linear model

x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.3940],
        [0.9937]], grad_fn=<AddmmBackward>)


In [30]:
# Practice: Use the linear regression model object lr 
# to make the prediction.

x = torch.tensor([[1.0],[2.0],[3.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.3940],
        [0.9937],
        [1.5934]], grad_fn=<AddmmBackward>)


In [31]:
#Build custom modules

In [32]:
# Library for this section

from torch import nn

In [33]:
# Customize Linear Regression Class

class LR(nn.Module):
    #Constructor
    def __init__(self, input_size, output_size):
        #Inherit from parent
        super(LR, self). __init__()
        self.linear = nn.Linear(input_size, output_size)
        
    
    #Prediction function
    def forward(self, x):
        out = self.linear(x)
        return out

In [35]:
# Create the linear regression model. 
# Print out the parameters.

lr = LR(1, 1)
print("The parameters: ", list(lr.parameters()))
print("Linear model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[0.5087]], requires_grad=True), Parameter containing:
tensor([0.1390], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [36]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.6478]], grad_fn=<AddmmBackward>)


In [37]:
# Try our customize linear regression model 
# with multiple input

x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.6478],
        [1.1565]], grad_fn=<AddmmBackward>)


In [39]:
print("Python dictionary: ", lr.state_dict())
print("Key: ", lr.state_dict().keys())
print("Value: ", lr.state_dict().values())

Python dictionary:  OrderedDict([('linear.weight', tensor([[0.5087]])), ('linear.bias', tensor([0.1390]))])
Key:  odict_keys(['linear.weight', 'linear.bias'])
Value:  odict_values([tensor([[0.5087]]), tensor([0.1390])])


In [ ]:
# Practice: Use the LR class to create a model 
# and make a prediction of the following tensor.

lr1 = LR(1, 1)
x = torch.tensor([[1.]])